drop table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_PRFact
create table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_PRFact
(
purchase_order_release_date date,
original_request_date date,
requisition_number_id varchar(255),
purchasing_document_id varchar(255),
vendor_part_number varchar(255),
delete_blocked_indicator_code varchar(255),
currency_code varchar(255),
company_code varchar(255),
plant_id varchar(255),
vendor_id varchar(255),
vendor_name varchar(255),
purchase_order_quantity float,
document_currency_net_price_amount float,
functional_currency_unit_price_amount float,
counts float,
timestamps timestamp
)

select * from s3dataschema.ods_Finance_Controlling_PRDelivery_IOBO
CREATE external TABLE s3dataschema.ods_Finance_Controlling_PRDelivery_IOBO
(
"Filepath" varchar(255),
"Filename" varchar(255),
"Submission date" varchar(255),
"Submission time" varchar(255),	
"Requestor name" varchar(255),	
"Act. Gds Mvmnt Date" varchar(255),	
"Approver name" varchar(255),	
"Approval Date" varchar(255),	
"Approval Time" varchar(255),	
"Ship Before Approval Indicator" varchar(255),	
"TED Profit Center" varchar(255),	
"Status" varchar(255),	
"Payment mode" varchar(255),	
"Delivery Document" varchar(255),	
"Delivery Document item" varchar(255),	
"Root cause" varchar(255),	
"Comments(Line 1)" varchar(255),	
"Freight Currency" varchar(255),	
"Freight Amount" varchar(255),	
"Net Price" varchar(255),	
"PF Carrier" varchar(255),	
"PF Carrier name" varchar(255),	
"PF Special proc. indicator" varchar(255),	
"Sold To Name" varchar(255),	
"Sales Office" varchar(255),	
"Ship from Country" varchar(255),	
"Ship To Name" varchar(255),	
"Ship to Country" varchar(255),	
"Material" varchar(255),	
"Warehouse" varchar(255),	
"Product hierarchy" varchar(255),	
"Product line" varchar(255),	
"Quantity" varchar(255),	
"Total Weight" varchar(255),	
"Sales Unit" varchar(255),	
"Profit Center" varchar(255),	
"Ship-to party" varchar(255),	
"Sold-to Party" varchar(255),	
"MRP Controller" varchar(255),	
"Sales Document" varchar(255),	
"Sales Document item" varchar(255),	
"Country of origin" varchar(255),	
"Sales Group" varchar(255),	
"Purchase Document" varchar(255),	
"Purchase Document item" varchar(255),	
"Customer Material" varchar(255),	
"Sales Organization" varchar(255),	
"Shipment Number" varchar(255),	
"External ID" varchar(255),	
"Delivery Date" varchar(255),	
"Plant Code" varchar(255),	
"Plant Name" varchar(255),	
"Premium Freight Flag" varchar(255),	
"Workitem ID" varchar(255),	
"Cust No at Carrier" varchar(255),	
"Freight Bill-to" varchar(255)

)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION 's3://te-aws-ss-prod-ts-aut-apac-digital-conformance-data/Apac_Digital/Finance_Department/FinanceCSV/Controlling/PR_Delivery_Automation_Report/Automation/ZSD4TR708/IB_OB/'; 

select * from s3dataschema.ods_Finance_Controlling_PRDelivery_SZPF
CREATE external TABLE s3dataschema.ods_Finance_Controlling_PRDelivery_SZPF
(
"Filepath" varchar(255),
"Filename" varchar(255),
"Delivery Document" varchar(255),
"Shipment Number" varchar(255),
"Requestor name" varchar(255),	
"Submission date" varchar(255),	
"Approval Date" varchar(255),	
"Approval Time" varchar(255),	
"Act. Gds Mvmnt Date" varchar(255),	
"Original Loading Date" varchar(255),	
"Freight Amount" varchar(255),	
"Freight Currency" varchar(255),	
"PF Carrier name" varchar(255),	
"PF Carrier" varchar(255),	
"Status" varchar(255),	
"Comments(Line 1)" varchar(255),	
"Ship-to party" varchar(255),	
"Sold-to Party" varchar(255),	
"Sold To Name" varchar(255),	
"Sales Document" varchar(255),	
"Purchase Document" varchar(255),	
"Material" varchar(255),	
"Quantity" varchar(255),	
"Delivery Date" varchar(255),	
"Shipment Carrier Name" varchar(255),	
"Root cause" varchar(255),	
"Comments(Line 2)" varchar(255),	
"Comments(Line 3)" varchar(255),	
"Comments(Line 4)" varchar(255),	
"Cancellation Date" varchar(255),	
"Cancelled By" varchar(255),	
"Freight Bill-to" varchar(255),	
"Loading Date" varchar(255),	
"Location id" varchar(255),	
"TMS LOAD ID" varchar(255),	
"Original Delivery Date" varchar(255),
"Plant Code" varchar(255),
"Premium Freight Flag" varchar(255),
"Profit Center" varchar(255),
"Rejected Date" varchar(255),
"Sales Organization" varchar(255),
"Ship To Name" varchar(255),
"Total Weight" varchar(255),
"Vendor" varchar(255),
"Weight unit" varchar(255),
"Workitem ID" varchar(255),
"Route" varchar(255)

)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION 's3://te-aws-ss-prod-ts-aut-apac-digital-conformance-data/Apac_Digital/Finance_Department/FinanceCSV/Controlling/PR_Delivery_Automation_Report/Automation/ZSD4TR708/SZ_PF/'; 

select * from ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_IOBO
drop table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_IOBO
 create  table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_IOBO
(
Filename varchar(255),
"Act. Gds Mvmnt Date" varchar(255),
"Approval Date" varchar(255),
 day_diff varchar(255),
"Ship Before Approval Indicator" varchar(255),
"Approval Time" varchar(255),
"TED Profit Center" varchar(255),
"Approver name" varchar(255),
"Status" varchar(255),
"Delivery Document" varchar(255),
"Delivery Document item" varchar(255),
"Root cause" varchar(255),
"Freight Currency" varchar(255),
"Freight Amount" float,
"Net Price" float,
"PF Carrier" varchar(255),
"PF Carrier name" varchar(255),
"PF Special proc. indicator" varchar(255),
"Requestor name" varchar(255),
"Submission date" varchar(255),
"Sold To Name" varchar(255),	
"Sales Office" varchar(255),	
"Ship from Country" varchar(255),	
"Ship To Name" varchar(255),	
"Ship to Country" varchar(255),	
"Material" varchar(255),	
"Warehouse" varchar(255),	
"Product hierarchy" varchar(255),	
"Product line" varchar(255),	
"Quantity" float,	
"Total Weight" float,	
"Sales Unit" varchar(255),	
"Profit Center" varchar(255),	
"Ship-to party" varchar(255),	
"Sold-to Party" varchar(255),	
"MRP Controller" varchar(255),	
"Sales Document" varchar(255),	
"Sales Document item" varchar(255),	
"Country of origin" varchar(255),	
"Sales Group" varchar(255),	
"Purchase Document" varchar(255),	
"Purchase Document item" varchar(255),	
"Customer Material" varchar(255),	
"Sales Organization" varchar(255),	
"Shipment Number" varchar(255),	
"External ID" varchar(255),	
"Delivery Date" varchar(255),	
"Plant Code" varchar(255),	
"Plant Name" varchar(255),	
"Premium Freight Flag" varchar(255),	
"Workitem ID" varchar(255),	
"Cust No at Carrier" varchar(255),	
"Freight Bill-to" varchar(255),
timestamps varchar(255)

)

SELECT * FROM ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_SZPF ORDER BY day_diff ASC LIMIT 1 OFFSET 1

SELECT * FROM ss_rs_ts_aut_ap_digital_schema.chat_history

drop table ss_rs_ts_aut_ap_digital_schema.chat_history
SELECT SUM(Quantity) AS total_quantity 
FROM ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_SZPF 
WHERE DATE_TRUNC('month', "Submission date") = DATE_TRUNC('month', CURRENT_DATE)

drop table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_SZPF
 create  table ss_rs_ts_aut_ap_digital_schema.DWD_Finance_Controlling_PRDelivery_SZPF
(
"Filename"  varchar(255),
"Delivery Document"  varchar(255),
"Shipment Number"  varchar(255),
"Requestor name"  varchar(255),	
"Submission date"  varchar(255),
"Act. Gds Mvmnt Date"  varchar(255),		
"Approval Date"  varchar(255),	
day_diff   varchar(255),
"Approval Time"  varchar(255),	
"Original Loading Date"  varchar(255),
"Freight Amount" float,	
"Freight Currency"  varchar(255),	
"PF Carrier name"  varchar(255),	
"PF Carrier"  varchar(255),	
"Status"  varchar(255),	
"Comments(Line 1)"  varchar(255),	
"Ship-to party"  varchar(255),	
"Sold-to Party"  varchar(255),	
"Sold To Name"  varchar(255),	
"Sales Document"  varchar(255),	
"Purchase Document"  varchar(255),	
"Material"  varchar(255),	
"Quantity" float,	
"Delivery Date"  varchar(255),	
"Shipment Carrier Name"  varchar(255),	
"Root cause"  varchar(255),	
"Comments(Line 2)"  varchar(255),	
"Comments(Line 3)"  varchar(255),	
"Comments(Line 4)"  varchar(255),	
"Cancellation Date"  varchar(255),	
"Cancelled By"  varchar(255),	
"Freight Bill-to"  varchar(255),	
"Loading Date"  varchar(255),	
"Location id"  varchar(255),	
"TMS LOAD ID"  varchar(255),	
"Original Delivery Date"  varchar(255),
"Plant Code"  varchar(255),
"Premium Freight Flag"  varchar(255),
"Profit Center"  varchar(255), 
"Rejected Date"  varchar(255),
"Sales Organization"  varchar(255),
"Ship To Name"  varchar(255),
"Total Weight" float,
"Vendor"  varchar(255),
"Weight unit"  varchar(255),
"Workitem ID"  varchar(255),
"Route"  varchar(255),
timestamps timestamp
)
