select count(*) from ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_ActualInternal_Engineeringallocation
drop table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_ActualInternal_Engineeringallocation
create table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_ActualInternal_Engineeringallocation
(
Fiscal_Yearmonth varchar(255),
Companycode varchar(255),	
"Ref. Document" varchar(255),	
"Fiscal Year" varchar(255),	
"Posting period" varchar(255),	
"Profit Center" varchar(255),	
"Account Number" varchar(255),	
"In company code currency" decimal(20,10),	
"Entry Date" varchar(255),	
"Posting Date" varchar(255),	
"Quantity" float,	
"Cost Center" varchar(255),	
"Functional Area" varchar(255),	
"WBS Element" varchar(255),
"PRJ NO" varchar(255),
BU varchar(255),
BU_Function varchar(255),
"location" varchar(255),
Department  varchar(255),
Team varchar(255),
"To_In company code currency" decimal(20,10),		
"To_Quantity" float,	
"To_WBS Element" varchar(255),
"To_PRJ NO" varchar(255),
"To_BU" varchar(255),
"To_BU_Function" varchar(255),
"To_location" varchar(255),
"To_Department" varchar(255),
"To_Team" varchar(255),
To_Companycode varchar(255),
"To_Profit Center" varchar(255),
"To_Functional Area" varchar(255),
"To_ProductLine" varchar(255),
"To_Project Name" varchar(255),
Phase varchar(255),
cny_usd_rate FLOAT,
twd_usd_rate FLOAT ,
"In company code currency CNY" decimal(20,10),
"To_In company code currency CNY" decimal(20,10),
Comments varchar(255),
timestamps timestamp
)
drop table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_ActualInternal_FinalActual
create table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_ActualInternal_FinalActual
(
fisical_Year varchar(255),
fisical_YearMonth varchar(255),
"location" varchar(255),
CostCenter2 varchar(255),
cost_center_category_code varchar(255),
"Department" varchar(255),
BU_Function varchar(255),
"Team" varchar(255),
Account varchar(255),
Description varchar(255),
AccountDescription varchar(255),
Months varchar(255),
cny_usd_rate float,
twd_usd_rate float,
Original_Amount float,
Amount_CNY float,
timestamps timestamp
)
drop table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_FinalFact
create table ss_rs_ts_aut_ap_digital_schema.DWS_Finance_FPA_Opex_FinalFact
(
Scenario varchar(255),
fisical_YearMonth varchar(255),
Department varchar(255),
BU_Function varchar(255),
Team varchar(255),
CostCenter2 varchar(255),
"Expense level 1" varchar(255),
"Expense level 2" varchar(255),	
Account varchar(255),	
"Accounts/Cost Elements" varchar(255),
Description varchar(255),
AccountDescription varchar(255),	
"Logic" varchar(255),	
"Index" varchar(255),	
"Comments" varchar(255),
budget_index2 float,
Budget_ActualAvg_budget_index3  decimal(25,10),
"Budget_Actual_total_index5-6"  decimal(25,10),
Budget_finalmonth_Actual_Index8  decimal(25,10),
Budget_ActualAvg_Salesv1_index9  decimal(25,10),
Budget_ActualAvg_Salesv1_index10  decimal(25,10),
Budget_Capexforecast_index7  decimal(25,10),
Budget_leasingforecast_index8  decimal(25,10),
Budget_eachmonth_index12  decimal(25,10),
budget_Allocations_index13  decimal(25,10),
Amount decimal(25,10),
commitRno_last_actual_amount  decimal(25,10),
commitRno_Labor_Amount_baseActual  decimal(25,10),
commitRno_Labor_Amount_baseOutlook  decimal(25,10),
commitRno_Avg_Actual_YTD_Amount_CNY  decimal(25,10),
commitRno_Manual_Forecast_Adj  decimal(25,10),
commitRno_Capex_Forecast_budget  decimal(25,10),
commitRno_Lease_Forecast_budget  decimal(25,10),
commitRno_YTD_Actual_Sales  decimal(25,10),
commitRno_last_Actual_salesamount  decimal(25,10),
commitRno_forecast_sales_amount  decimal(25,10),
commitRno_outlook_Budget_Final  decimal(25,10),
commitRno_EngineeringAllocations_forecast_manualAdj  decimal(25,10),
commitRno_des1 varchar(255),
commitRno_des2 varchar(255),
commitRno_Budget_BaseonActual  decimal(25,10),
commitRno_Budget_Baseonoutlook  decimal(25,10),
timestamps timestamp
)